version: '3'
volumes:
  data:
services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nestjs
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  elastic:
    image: softwaremill/elasticmq
    volumes:
      - ./elastic.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
      - "9325:9325"
